sudo: required

language: java

services:
  - docker

install:
  - docker run --name some-postgres -h localhost -e POSTGRES_HOST=127.0.0.1 -e POSTGRES_PORT=5432 -e POSTGRES_USER=postgres -e  POSTGRES_PASSWORD=postgres -e POSTGRES_DB=kurs_tracks -d postgres:9.3
  - docker run --link some-postgres:postgres -d --name tomcat tomcat
  - mvn package 
  - cp target/component-service-tracks-1.0.0-SNAPSHOT.jar src/main/docker
  - docker build -t my_app_component_service_tracks src/main/docker

script:
  - docker run --link tomcat:tomcat --link some-postgres:postgres my_app_component_service_tracks /bin/sh
